#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

main_domain=$(cat /etc/yunohost/current_host)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Platform for file storage" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# INSTALL SYNC_IN
#=================================================
ynh_script_progression "Upgrading the app..."

ynh_replace --match="\"@sync-in\\/server\": .*" --replace="\"@sync-in\\/server\": \"$(ynh_app_upstream_version)\"" --file="$install_dir/package.json"
ynh_safe_rm $install_dir/node_modules
ynh_safe_rm $install_dir/package-lock.json

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install #--prefix ./sync-in
	ynh_hide_warnings ynh_exec_as_app npx sync-in-server migrate-db
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
